version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: 
          name: Install npm dependencies
          command: |
            npm install --save
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker Image
          command: |
            docker build -t circleci_prac1 -t sid716/circleci_prac1:latest .
            echo $DOCKER_PASSWORD | docker login -u sid716 --password-stdin
            docker push sid716/circleci_prac1:latest            


workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image

